# PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: mrbrown
  password: 12345678

development:
  <<: *default
  database: enliven_development

test:
  <<: *default
  database: enliven_test

production:
  <<: *default
  database: enliven_production
  username: enliven
  password: <%= ENV['ENLIVEN_DATABASE_PASSWORD'] %>
